name: Deploy to ECS with Fargate Capacity

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Create .PEM File
        run: wget https://truststore.pki.rds.amazonaws.com/ap-southeast-1/ap-southeast-1-bundle.pem

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_AK_ID }}
          aws-secret-access-key: ${{ secrets.AWS_AK_SECRET }}
          aws-region: ap-southeast-1

      - name: Authenticate with AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: private

      - name: Build, Tag, & Push Docker Image to ECR
        id: build-tag-push
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPO: ecs_go_pg
          TAG: ${{ github.sha }}
        run: |
          echo "container_url=$(echo $REGISTRY)/$(echo $REPO):$(echo $TAG)" >> $GITHUB_ENV
          docker build -t $REGISTRY/$REPO:$TAG .
          docker push $REGISTRY/$REPO:$TAG

      # - name: Run Terraform
      #   env:
      #     TAG: ${{ steps.build-tag-push.outputs.container_url }}
      #   run: |
      #     terraform init
      #     terraform apply --auto-approve
        
